/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/


#include<stdio.h>
#include<stdint.h>

/* This function executes in THREAD MODE of the processor */
void generate_interrupt()
{
	//Almaceno direccion del registro ISER. ISER Habilita la interrupcion de ese IRQ
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//Almaceno direccion del registro STIR. STIR: Genera interrupciones por software.
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;

	//Habilito IRQ3 interrupt correspondiente a RTC_WKUP
	*pISER0 |= ( 1 << 3);

	//Genero Interrupcion por software para IRQ3
	*pSTIR = (3 & 0x1FF);
}


void change_access_level_unpriv(void)
{

	//read
	__asm volatile ("MRS R0,CONTROL");
	//modify
	__asm volatile ("ORR R0,R0,#0x01");
	//write
	__asm volatile ("MSR CONTROL,R0");

}

/* This function executes in THREAD MODE+ PRIV ACCESS LEVEL of the processor */
int main(void)
{
	printf("In thread mode : before interrupt\n");

	change_access_level_unpriv();

	generate_interrupt();

	printf("In thread mode : after interrupt\n");

	for(;;);
}

/* This function(ISR) executes in HANDLER MODE of the processor */
void RTC_WKUP_IRQHandler(void)
{
	printf("In handler mode : ISR\n");
}

void HardFault_Handler(void)
{
	printf("Hard fault detected\n");
	while(1);
}
