/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

/*
Write a program to execute an SVC instruction from thread mode,
implement the svc handler to print the SVC number used.
Also,  increment the SVC number by 4 and return it to the thread mode code and print it.
Hints :
1)Write a main() function where you should execute the SVC instruction with an argument.
let's say SVC #0x5
2)Implement the SVC handler
3)In the SVC handler extract the SVC number and print it using printf
4) Increment the SVC number by 4 and return it to the thread mode
*/

#include<stdio.h>
#include<stdint.h>
int main(void)
{

	//Genero interrupcion SVC
	__asm volatile ("SVC #25");

	//Recupero valor de numero SVC de R0
	//register uint32_t data __asm("r0");
	uint32_t data;
	__asm volatile ("MOV %0,R0": "=r"(data) ::);
	printf(" data = %ld\n",data);

	for(;;);
}


__attribute__ ((naked)) void SVC_Handler(void)
{
	//1 . get the value of the MSP
	__asm("MRS R0,MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame)
{
	printf("in SVC handler\n");


	//pBaseOfStackFrame[6] es la ubicacion de PC
	uint8_t *pReturn_addr = (uint8_t*)pBaseOfStackFrame[6];

	//2. decrement the return address by 2 to point to
	//opcode of the SVC instruction in the program memory
	pReturn_addr-=2;

	//3. extract the SVC number (LSByte of the opcode)
    uint8_t svc_number = *pReturn_addr;

    printf("Svc number is : %d\n",svc_number);

    //Regreso o mantengo el valor despues de salir de Handler
    //Recodar que esta funcion es local
    //pBaseOfStackFrame[0] es la ubicacion de R0
    //R0 sera mantendra su valor para ser llamado por una variable C.
    pBaseOfStackFrame[0] = svc_number;

}
