/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
/*
#define SRAM_START 				0x20000000U
#define SRAM_SIZE  				(128 * 1024)
#define SRAM_END  				( (SRAM_START) + (SRAM_SIZE) )
#define STACK_START SRAM_END

#define STACK_MSP_START 		 STACK_START
#define STACK_MSP_END   		(STACK_MSP_START - 512)
#define STACK_PSP_START 		STACK_MSP_END
*/
int fun_add(int a, int b , int c , int d)
{
	return a+b+c+d;
}

/* this function changes SP to PSP */
__attribute__((naked)) void change_sp_to_psp(void)
{
	//Inicializo el final del stack de la RAM propuesto
	__asm volatile(".equ SRAM_END, (0x20000000 + ( 128 * 1024))");
	//Inicializo el inicio del stack de la RAM de PSP
	__asm volatile(".equ PSP_START, (SRAM_END-512)");
	//Escribo direccion del comienzo de PSP en R0
	__asm volatile("LDR R0,=PSP_START");
	//Copio R0 en PSP (Hago efectivo el inicio de PSP)
	__asm volatile("MSR PSP, R0");
	//Copio 0x02 en R0
	__asm volatile("MOV R0,#0X02");
	//Escribo en CONTROL el valor de R0
	//Hago efectivo que el puntero a utilizar es PSP
	//CONTROL Bit[1] = 1 (PSP)
	//CONTROL Bit[1] = 0 (MSP)
	__asm volatile("MSR CONTROL,R0");
	//Escribo en PC el valor de LR
	//LR almacena el retorno de la funcion
	//Sigue en el main la siguiente instruccion
	__asm volatile("BX LR");

}

void generate_exception(void)
{
	/* execute SVC instruction to cause SVC exception */
	__asm volatile("SVC #0X2");
}

int main(void)
{
	change_sp_to_psp();

/* from here onwards PSP will be used for stack activities */
	int ret;

	ret = fun_add(1, 4, 5, 6);

	printf("result = %d\n",ret);

	generate_exception();

	for(;;);
}


void SVC_Handler(void)
{
	printf(" in SVC_Handler\n");
}
