/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
#include<stdint.h>

/* This function executes in THREAD MODE of the processor */
void generate_interrupt()
{
	//Almaceno direccion del registro ISER. ISER Habilita la interrupcion de ese IRQ
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//Almaceno direccion del registro STIR. STIR: Genera interrupciones por software.
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;

	//Habilito IRQ3 interrupt correspondiente a RTC_WKUP
	*pISER0 |= ( 1 << 3);

	//Genero Interrupcion por software para IRQ3
	*pSTIR = (3 & 0x1FF);
}

/* This function executes in THREAD MODE of the processor */
int main(void)
{
	//Inicia main, modo thread
	printf("In thread mode : before interrupt\n");

	//Executo interrupcion para modo Handler
	//xPRS tendra datos en los primeros 8 bits
	//Vease registro IPSR [8:0]
	//ISR_NUMBER[0] = 0 Thread
	//ISR_NUMBER[0] != 0 Handler

	generate_interrupt();

	//despues de la interrupcion vuelvo a main, modo thread
	printf("In thread mode : after interrupt\n");

	for(;;);
}

/* This function(ISR) executes in HANDLER MODE of the processor */
void RTC_WKUP_IRQHandler(void)
{
	printf("In handler mode : ISR\n");
}

